[package]
name = "winptyrs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/andfoy/winpty-rs"
repository = "https://github.com/andfoy/winpty-rs"
description = "Rust-idiomatic wrapper around winpty"
readme = "README.md"
keywords = ["windows", "pty", "winpty", "pseudoterminal"]

[features]
default = ["vendored"]
vendored = ["winptyrs-sys/vendored"]

[dependencies]
bitflags = "2.3"
thiserror = "2.0"
winptyrs-sys = { path = "../winptyrs-sys", version = "0.1.0" }

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.61"
features = [
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Console",
    "Win32_System_IO",
    "Win32_System_Pipes",
    "Win32_System_Threading",
]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-gnu"
targets = ["x86_64-pc-windows-gnu"]
