[workspace]
members = [
    "crates/winptyrs-sys",
    "crates/winptyrs",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/andfoy/winpty-rs"
repository = "https://github.com/andfoy/winpty-rs"

[workspace.metadata.docs.rs]
default-target = "x86_64-pc-windows-gnu"
targets = ["x86_64-pc-windows-gnu"]
